### ISSUE TITLE
process_changed_mods no need to download YangModels Github

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/search#17]
... as it is already in /var/yang

**Comment by miroslavKovacPantheon** [comment]
process_changed_mods does not download yangModels as far as I know. It only pulls the newest changes if there are any..  Where did you see the downloading?

**Comment by miroslavKovacPantheon** [comment]
We are cloning the yangModule/yang repository only with draftPull job. We need to create a separate new clone of this repository because we are adding new modules to the repo in here and creating automated pull request. There is a Travis job that determines wether modules are fine or not. If not then this pull request is not merged with main yangModel/yang repository. If we do this with our /var/yang /nonietf  repo and travis job would fail we would have discrapancy with modules that are in repository and module that are in server clone of the repo.

Closing this as invalid
thank you
