### ISSUE TITLE
yang impact analysis is missing dependencies

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/search#71]
This shows that bbf-ancp imports bbf-yang-types: https://yangcatalog.org/yang-search/impact_analysis/?modtags=bbf-ancp&orgtags=&recursion=&show_dir=both

But this shows nothing connected to bbf-yang-types: https://yangcatalog.org/yang-search/impact_analysis/?modtags=bbf-yang-types&orgtags=&recursion=0&show_dir=both

Another (possibly related) problem. If I do this, I see just the module, and not its bbf-ancp import: https://yangcatalog.org/yang-search/impact_analysis/?modtags=bbf-ancp-fastdsl-access-extensions&orgtags=&recursion=&show_dir=both

If I do this, I see bbf-ancp and its imports, but not the things that import it: https://yangcatalog.org/yang-search/impact_analysis/?modtags=bbf-ancp&orgtags=&recursion=0&show_dir=both

If I do this I get an error: https://yangcatalog.org/yang-search/impact_analysis/?modtags=bbf-ancp%2C+bbf-ancp-fastdsl-threshold%2Cbbf-ancp-fastdsl-access-extensions%2Cbbf-ancp-interfaces&orgtags=&recursion=0&show_dir=both

(Actually the thing I was going to give as the third example was just the first two modules specified together. I thought it too gave an error. Maybe I chose the wrong two. But anyway I’m able to demonstrate the error with the four modules, so I’ll leave it there. Thanks.)

**Comment by richardzilincikPantheon** [comment]
The first 4 links work correctly now. The last link shows an error, because it includes an extra space before the module name. When this is removed, it works fine: https://yangcatalog.org/yang-search/impact_analysis?modtags=bbf-ancp,bbf-ancp-fastdsl-threshold,bbf-ancp-fastdsl-access-extensions,bbf-ancp-interfaces&orgtags=&recursion=0&show_dir=both
@SlavomirMazurPantheon this issue can be closed.

**Comment by SlavomirMazurPantheon** [comment]
Closing issue - already fixed.
